'use client';
import { Activity,Clock,ExternalLink,Radio } from 'lucide-react';
import { role,templates,type AgentId,type Snapshot } from '@office/contracts';

export default function AgentWorkPanel({data,id,live,now,syncedAt,syncError,onRefresh}:{data:Snapshot;id:AgentId;live:boolean;now:number;syncedAt:number;syncError:boolean;onRefresh:()=>void}){
 const tasks=data.tasks.filter(t=>t.agent_id===id).sort((a,b)=>Date.parse(b.updated_at)-Date.parse(a.updated_at));
 const task=tasks.find(t=>t.status==='working')??tasks.find(t=>t.status==='queued')??tasks.find(t=>t.status==='blocked')??tasks[0];
 const worker=data.workers.find(w=>!w.revoked&&w.capabilities.progress&&typeof w.capabilities.progress==='object'&&(w.capabilities.progress as Record<string,unknown>).task_id===task?.id);
 const progress=worker?.capabilities.progress as Record<string,unknown>|undefined;
 const fresh=!!worker?.last_seen&&now-Date.parse(worker.last_seen)<45000;
 const previous=task?data.tasks.find(t=>t.objective_id===task.objective_id&&t.step===task.step-1):undefined;
 const events=data.events.filter(e=>tasks.some(t=>t.id===e.payload.task_id)).slice(0,5);
 const stale=live&&(syncError||!syncedAt||now-syncedAt>20000);
 const stage=task?.status==='working'?(fresh&&typeof progress?.stage==='string'?progress.stage:'Waiting for a worker update'):task?.status==='queued'?'Waiting for the laptop':task?.status==='blocked'?`Waiting for ${previous?role(previous.agent_id).name:'the previous handoff'}`:task?.status==='failed'?'Handoff stopped':task?.status==='completed'?'Handoff complete':task?.status==='cancelled'?'Objective cancelled':'No assigned work';
 const draft=task?.status==='working'&&typeof progress?.draft==='string'?progress.draft:'';
 return <section className="agent-live-panel" aria-label="Agent live work">
  <div className="work-live-header"><span><Radio size={14}/>{live?stale?'Updates delayed':'Live work':'Sample work'}</span><button onClick={onRefresh} type="button" disabled={!live}>Refresh</button></div>
  <p className="work-update-time">{live?`Last synced ${syncedAt?new Date(syncedAt).toLocaleTimeString():'—'} · refreshes every 3 seconds`:'Demonstration only. No real execution.'}</p>
  {task?<article className="work-card-task"><div className="row between"><span className="eyebrow">{templates[task.template].name}</span><span className={`status status-${task.status}`}>{task.status}</span></div><h3>{task.title.length>180?task.title.slice(0,177)+'…':task.title}</h3>{task.title.length>180&&<details><summary>Read full objective</summary><p>{task.title}</p></details>}<div className="work-stage"><Activity size={14}/><strong>{stage}</strong></div>{task.status==='working'&&<p className="work-elapsed"><Clock size={13}/>{Math.max(0,Math.floor((now-Date.parse(task.updated_at))/1000))} seconds since the handoff started</p>}{task.status==='working'&&fresh&&typeof progress?.detail==='string'&&<p>{progress.detail}</p>}{task.status==='working'&&!fresh&&live&&<p className="work-warning">No recent task report. The laptop may be reconnecting; this status does not confirm current processing.</p>}{task.status==='queued'&&<p>{data.workers.some(w=>!w.revoked&&w.last_seen&&now-Date.parse(w.last_seen)<120000)?'The laptop runs one handoff at a time. This work will be picked up when it is available.':'Keep the paired laptop awake and start its worker to pick up this work.'}</p>}{task.status==='blocked'&&<p>This agent starts after the preceding handoff completes.</p>}{task.error&&<p className="error-inline">{task.error}</p>}{draft&&<div className="work-draft"><span className="eyebrow">DRAFT IN PROGRESS · NOT YET VALIDATED</span><pre>{draft}</pre></div>}</article>:<p className="card-empty">No assigned work. Create an objective for this team.</p>}
  {events.length>0&&<div className="work-events"><h3>Recent activity</h3><ol>{events.map(e=><li key={e.id}><time>{new Date(e.created_at).toLocaleTimeString()}</time><span>{e.kind==='task.started'?'Handoff started':e.kind==='task.completed'?'Handoff saved':e.kind==='task.failed'?'Handoff failed':e.kind.replaceAll('.',' ')}</span></li>)}</ol></div>}
  {tasks.filter(t=>t.output).slice(0,3).map(t=><article className="work-card-task" key={t.id}><span className="eyebrow">SAVED HANDOFF · {new Date(t.updated_at).toLocaleString()}</span><h3>{t.output!.summary}</h3>{t.output!.lead_batch&&<div className="lead-export"><p>{t.output!.lead_batch.rows.length} opportunities · company-size checks included</p><a className="button primary" href={`/api/leads/${t.id}/export`}>Download Excel</a>{t.output!.lead_batch.rows.slice(0,3).map(row=><p key={row.url}><strong>{row.title}</strong><br/>{row.market} · {row.company_size}</p>)}</div>}<details><summary>Read the full work</summary><pre>{t.output!.deliverable}</pre>{t.output!.limitations.map((value,i)=><p className="limitation" key={i}>{value}</p>)}{t.output!.sources.map(s=><a key={s.url} href={s.url} rel="noreferrer" target="_blank" className="source-link">{s.title}<ExternalLink size={12}/></a>)}</details></article>)}
 </section>;
}
