'use client';
import { Component,useRef,useState,useEffect,type ReactNode } from 'react';
import { Canvas,useFrame,useThree } from '@react-three/fiber';
import { RoundedBox,Html,ContactShadows,OrbitControls } from '@react-three/drei';
import * as THREE from 'three';
import { agents,type AgentId } from '@office/contracts';
const stations:[number,number][]=[[-2,-6],[-8,6],[-5,6],[-9,-6],[-5.8,-6],[-9,-2.5],[-5.8,-2.5],[3.8,-6],[7,-6],[10.2,-6],[3.8,-2.5],[7,-2.5],[10.2,-2.5],[7,1],[10.2,1],[3.8,6],[7,6],[10.2,6]];
type Person=Record<'name'|'role'|'short'|'color',string>&{id:AgentId|'ceo'};
const ceo:Person={id:'ceo',name:'You',role:'Chief Executive Officer',short:'CEO',color:'#c9a55f'};
function Block({size,position,color,radius=.06,metalness=0}:{size:[number,number,number];position:[number,number,number];color:string;radius?:number;metalness?:number}){return <RoundedBox args={size} radius={radius} smoothness={3} position={position}><meshStandardMaterial color={color} roughness={metalness?.35:.65} metalness={metalness}/></RoundedBox>;}
function Plant({position}:{position:[number,number,number]}){return <group position={position}><mesh position={[0,.22,0]}><cylinderGeometry args={[.28,.2,.44,12]}/><meshStandardMaterial color="#d5d5c7"/></mesh>{[0,1,2,3].map(i=><mesh key={i} position={[Math.sin(i*2)*.18,.65+i*.14,Math.cos(i*2)*.14]}><sphereGeometry args={[.32,10,8]}/><meshStandardMaterial color={i%2?'#6b8772':'#8aa28b'}/></mesh>)}</group>;}
function Keyboard(){const keys=useRef<THREE.InstancedMesh>(null);useEffect(()=>{if(!keys.current)return;const transform=new THREE.Object3D();for(let row=0;row<3;row++)for(let col=0;col<10;col++){transform.position.set(-.24+col*.053,.022,-.067+row*.055);transform.updateMatrix();keys.current.setMatrixAt(row*10+col,transform.matrix);}keys.current.instanceMatrix.needsUpdate=true;},[]);return <group position={[0,.69,.16]}><Block size={[.58,.03,.22]} position={[0,0,0]} color="#3b4548" radius={.018}/><instancedMesh ref={keys} args={[undefined,undefined,30]}><boxGeometry args={[.043,.013,.043]}/><meshStandardMaterial color="#e5e7df"/></instancedMesh><Block size={[.21,.012,.035]} position={[0,.022,.095]} color="#9eaaa4" radius={.005}/></group>;}
function Desk({position,active,executive=false,creative=false,dark=false}:{position:[number,number];active:boolean;executive?:boolean;creative?:boolean;dark?:boolean}){const [x,z]=position;return <group position={[x,.32,z]} scale={executive?1.65:1.35}>
<Block size={[executive?1.9:1.65,.11,.9]} position={[0,.62,0]} color={executive?'#997851':dark?'#45535a':'#fafaf6'}/>{[-.66,.66].map(v=><Block key={v} size={[.07,.57,.67]} position={[v,.29,0]} color={dark?'#455158':'#bac6bf'} radius={.015}/>)}
<Block size={[.78,.5,.06]} position={[0,1.02,-.16]} color="#2c383d" radius={.03}/><Block size={[.7,.42,.015]} position={[0,1.02,-.121]} color={dark?'#142f36':active?'#d0e8de':'#dfe7e0'} radius={.012}/>{[0,1,2,3].map(i=><Block key={i} size={[creative?.49:i===0?.29:.46,.021,.01]} position={[-.025,1.15-i*.074,-.107]} color={creative?['#cb8fac','#dcb368','#96b1ca','#aa9fc2'][i]:active?'#68a692':'#9aad9f'} radius={.006}/>)}<Block size={[.05,.22,.05]} position={[0,.77,-.16]} color="#71857b"/><Block size={[.28,.02,.15]} position={[0,.67,-.16]} color="#75857c"/><Keyboard/>
<Block size={[.1,.04,.15]} position={[.43,.7,.18]} color="#667876" radius={.04}/><Block size={[.2,.018,.24]} position={[-.52,.685,.15]} color={creative?'#b992b5':'#ebdfc2'} radius={.01}/><mesh position={[.63,.75,-.1]}><cylinderGeometry args={[.065,.055,.15,12]}/><meshStandardMaterial color={executive?'#d1b474':'#b79878'}/></mesh><Block size={[.24,.48,.42]} position={[.48,.27,-.08]} color={dark?'#263439':'#91a49a'}/>
<Block size={[.53,.09,.47]} position={[0,.47,.98]} color={executive?'#424948':dark?'#536970':'#8fa99a'} radius={.09}/><Block size={[.53,.48,.1]} position={[0,.76,1.2]} color={executive?'#424948':dark?'#536970':'#8fa99a'} radius={.08}/><mesh position={[0,.22,1]}><cylinderGeometry args={[.04,.04,.43,10]}/><meshStandardMaterial color="#5c6b67" metalness={.3}/></mesh>
{executive&&<><Block size={[.36,.025,.3]} position={[-.7,.7,.1]} color="#253935"/><Block size={[.08,.12,.08]} position={[.8,.73,-.15]} color="#c9a55f" metalness={.7}/></>}</group>;}
function Robot({person,index,station,active,selected,onSelect,reduced,labelsReady,immersive=false,preview=false,executive=false}:{person:Person;index:number;station:[number,number];active:boolean;selected:boolean;onSelect:(id:AgentId|'ceo')=>void;reduced:boolean;labelsReady:boolean;immersive?:boolean;preview?:boolean;executive?:boolean}){
const root=useRef<THREE.Group>(null),torso=useRef<THREE.Group>(null),head=useRef<THREE.Group>(null),leftArm=useRef<THREE.Group>(null),rightArm=useRef<THREE.Group>(null),leftLeg=useRef<THREE.Group>(null),rightLeg=useRef<THREE.Group>(null),leftEye=useRef<THREE.Mesh>(null),rightEye=useRef<THREE.Mesh>(null);
const [hovered,setHovered]=useState(false),stride=useRef(0),[x,z]=station,scale=executive?1.65:1.35,homeZ=z+.62*scale;
useFrame(({clock},delta)=>{const g=root.current;if(!g)return;const dt=Math.min(delta,.05),t=clock.elapsedTime+index*3.7,phase=t%64,walking=active&&!reduced&&!executive&&phase>48,travel=walking?Math.sin((phase-48)/16*Math.PI):0;
const tx=x+Math.sin((phase-48)/16*Math.PI*2)*.6*travel,tz=homeZ+travel*1.15,beforeX=g.position.x,beforeZ=g.position.z;
g.position.x=THREE.MathUtils.damp(g.position.x,walking?tx:x,4,dt);g.position.z=THREE.MathUtils.damp(g.position.z,walking?tz:homeZ,4,dt);
const dx=g.position.x-beforeX,dz=g.position.z-beforeZ,speed=Math.hypot(dx,dz)/Math.max(dt,.001),moving=!reduced&&speed>.025;stride.current+=speed*dt*9;const gait=Math.sin(stride.current),heading=moving?Math.atan2(dx,dz):active?Math.PI:0;
const angle=Math.atan2(Math.sin(heading-g.rotation.y),Math.cos(heading-g.rotation.y));g.rotation.y+=angle*(1-Math.exp(-5*dt));g.position.y=.33+(moving?Math.abs(gait)*.018:0);
if(torso.current){torso.current.rotation.z=THREE.MathUtils.damp(torso.current.rotation.z,moving?gait*.025:0,5,dt);torso.current.position.y=reduced?0:Math.sin(t*1.6)*.006;}if(head.current){head.current.rotation.y=THREE.MathUtils.damp(head.current.rotation.y,reduced?0:moving?0:Math.sin(t*.6)*.12,4,dt);head.current.rotation.x=THREE.MathUtils.damp(head.current.rotation.x,active&&!moving?.08:0,4,dt);}
if(leftLeg.current)leftLeg.current.rotation.x=THREE.MathUtils.damp(leftLeg.current.rotation.x,moving?gait*.43:0,10,dt);if(rightLeg.current)rightLeg.current.rotation.x=THREE.MathUtils.damp(rightLeg.current.rotation.x,moving?-gait*.43:0,10,dt);const typing=active&&!moving&&!reduced;
if(leftArm.current)leftArm.current.rotation.x=THREE.MathUtils.damp(leftArm.current.rotation.x,moving?-gait*.36:typing?-1.35+Math.sin(t*9)*.045:.08,10,dt);if(rightArm.current)rightArm.current.rotation.x=THREE.MathUtils.damp(rightArm.current.rotation.x,moving?gait*.36:typing?-1.35+Math.sin(t*9+Math.PI)*.045:.08,10,dt);
const blink=reduced?1:t%7.4>7.23?.12:1;if(leftEye.current)leftEye.current.scale.y=blink;if(rightEye.current)rightEye.current.scale.y=blink;});
return <group ref={root} position={[x,.33,homeZ]} scale={scale} onClick={e=>{e.stopPropagation();onSelect(person.id);}} onPointerOver={e=>{e.stopPropagation();setHovered(true);}} onPointerOut={()=>setHovered(false)}>
<mesh rotation={[-Math.PI/2,0,0]} position={[0,.015,0]}><circleGeometry args={[.32,24]}/><meshBasicMaterial color="#162c28" transparent opacity={.12}/></mesh><group ref={torso}>
<Block size={[.44,.43,.33]} position={[0,.55,0]} color={person.color} radius={.13} metalness={.15}/><Block size={[.25,.19,.02]} position={[0,.58,.174]} color={executive?'#263b3c':'#e4e6dc'} radius={.035}/><mesh position={[0,.6,.189]}><circleGeometry args={[.043,16]}/><meshStandardMaterial color={active?'#b5f2de':executive?'#d8bf7a':'#6a8478'} emissive={active?'#77d1b0':'#000000'} emissiveIntensity={.35}/></mesh><Block size={[.18,.07,.2]} position={[0,.81,0]} color="#536965" radius={.025}/>
<group ref={head} position={[0,.9,0]}><Block size={[.6,.43,.42]} position={[0,.08,0]} color={person.color} radius={.16} metalness={.15}/><Block size={[.46,.26,.035]} position={[0,.09,.214]} color="#1d3033" radius={.085}/><mesh ref={leftEye} position={[-.11,.115,.24]}><sphereGeometry args={[.035,12,10]}/><meshBasicMaterial color={preview?'#a8bdc1':'#b9f9e6'}/></mesh><mesh ref={rightEye} position={[.11,.115,.24]}><sphereGeometry args={[.035,12,10]}/><meshBasicMaterial color={preview?'#a8bdc1':'#b9f9e6'}/></mesh><Block size={[.07,.012,.015]} position={[0,.025,.24]} color="#72a4a0" radius={.005}/><mesh position={[0,.34,0]}><sphereGeometry args={[.036,10,8]}/><meshStandardMaterial color={executive?'#e4c978':'#a5c8be'} emissive={active?'#69c8a0':'#000000'} emissiveIntensity={.25}/></mesh>{[-.315,.315].map(v=><mesh key={v} position={[v,.07,0]} rotation={[0,0,Math.PI/2]}><cylinderGeometry args={[.075,.075,.05,12]}/><meshStandardMaterial color="#728781" metalness={.5}/></mesh>)}</group>
{[{ref:leftArm,x:-.31},{ref:rightArm,x:.31}].map((a,i)=><group ref={a.ref} key={i} position={[a.x,.72,0]}><mesh><sphereGeometry args={[.08,10,10]}/><meshStandardMaterial color="#688078" metalness={.3}/></mesh><Block size={[.12,.23,.13]} position={[0,-.14,0]} color={person.color} radius={.045}/><Block size={[.15,.13,.17]} position={[0,-.31,-.02]} color="#dce2d7" radius={.05}/></group>)}</group>
{[{ref:leftLeg,x:-.13},{ref:rightLeg,x:.13}].map((a,i)=><group ref={a.ref} key={i} position={[a.x,.34,0]}><Block size={[.14,.21,.15]} position={[0,-.12,0]} color={person.color} radius={.04}/><Block size={[.19,.1,.27]} position={[0,-.26,.045]} color="#354b49" radius={.04}/></group>)}
{(selected||hovered)&&<mesh rotation={[-Math.PI/2,0,0]} position={[0,.03,0]}><ringGeometry args={[.41,.45,48]}/><meshBasicMaterial color={executive?'#d5b76f':'#67c6ab'} transparent opacity={.85}/></mesh>}{labelsReady&&(!immersive||hovered)&&<Html position={[0,1.6,0]} center style={{pointerEvents:'auto'}}><button className={`scene-label ${selected?'selected':''} ${executive?'ceo-label':''}`} onClick={()=>onSelect(person.id)} aria-label={`Select ${person.name}, ${person.role}`}><i style={{background:person.color}}/>{person.short}{preview&&<small>preview</small>}{active&&<span className="label-dot"/>}</button></Html>}</group>;}
class SceneBoundary extends Component<{children:ReactNode;fallback:ReactNode},{failed:boolean}>{state={failed:false};static getDerivedStateFromError(){return {failed:true};}render(){return this.state.failed?this.props.fallback:this.props.children;}}
function CameraRig({zoom,onZoomChange}:{zoom:number;onZoomChange:(value:number)=>void}){
 const {camera,size}=useThree(),fit=Math.min(size.width/33,size.height/24),applied=useRef(''),sample=useRef({seconds:0,frames:0});
 useFrame((state,delta)=>{const key=fit+':'+zoom;if(applied.current!==key&&state.camera instanceof THREE.OrthographicCamera){state.camera.zoom=fit*(zoom/45);state.camera.updateProjectionMatrix();applied.current=key;}sample.current.seconds+=delta;sample.current.frames++;if(sample.current.seconds>=1){state.gl.domElement.dataset.frameMs=(sample.current.seconds*1000/sample.current.frames).toFixed(1);state.gl.domElement.dataset.cameraPosition=state.camera.position.toArray().map(n=>n.toFixed(1)).join(',');sample.current={seconds:0,frames:0};}});
 return <OrbitControls makeDefault enablePan enableZoom enableDamping dampingFactor={.08} minZoom={fit*.55} maxZoom={fit*5} minPolarAngle={.42} maxPolarAngle={1.25} target={[.5,.3,.7]} onEnd={()=>{if(camera instanceof THREE.OrthographicCamera)onZoomChange(THREE.MathUtils.clamp(Math.round(camera.zoom/fit*45),25,225));}}/>;
}
export default function OfficeScene({activeIds,selected,onSelect,zoom,onZoomChange,reduced,dark=false,immersive=false,ceoOnline=false}:{activeIds:AgentId[];selected:AgentId;onSelect:(id:AgentId|'ceo')=>void;zoom:number;onZoomChange:(value:number)=>void;reduced:boolean;dark?:boolean;immersive?:boolean;ceoOnline?:boolean}){
const [supported,setSupported]=useState(true),[labelsReady,setLabelsReady]=useState(false),[visible,setVisible]=useState(true);useEffect(()=>{const c=document.createElement('canvas');const gl=c.getContext('webgl2');if(!gl){const timer=setTimeout(()=>setSupported(false),0);return()=>clearTimeout(timer);}gl.getExtension('WEBGL_lose_context')?.loseContext();},[]);useEffect(()=>{const change=()=>setVisible(!document.hidden);document.addEventListener('visibilitychange',change);return()=>document.removeEventListener('visibilitychange',change);},[]);
const fallback=<div className="floor-fallback"><span>Office floor</span><p>Use the team list to follow and select your agents.</p><div>{agents.map(a=><button key={a.id} onClick={()=>onSelect(a.id)}><i style={{background:a.color}}/>{a.name}<small>{a.short}</small></button>)}</div></div>;if(!supported)return fallback;
return <SceneBoundary fallback={fallback}><Canvas onCreated={()=>setTimeout(()=>setLabelsReady(true),0)} frameloop={visible?'always':'never'} dpr={[1,1.4]} orthographic camera={{position:[21,26,30],zoom,near:.1,far:150}} gl={{antialias:true,powerPreference:'low-power'}} aria-label="Interactive 18-agent office with a central CEO desk. Drag to orbit, scroll or pinch to zoom, click a robot for its work card, Escape to leave immersive view.">
<CameraRig zoom={zoom} onZoomChange={onZoomChange}/><color attach="background" args={[dark?'#101c27':'#e9ede7']}/><ambientLight intensity={dark?.9:1.45}/><directionalLight position={[6,16,8]} intensity={dark?1.8:2.1} color={dark?'#b9d3ef':'#fff6e7'}/><directionalLight position={[-10,8,-5]} intensity={dark?1.2:.7} color="#bce7dc"/>
<group position={[.4,-.1,.5]}><Block size={[27,.38,21]} position={[0,0,0]} color={dark?'#273847':'#bcc9ba'} radius={.25}/><Block size={[26.8,.1,20.8]} position={[0,.23,0]} color={dark?'#5aada4':'#89b39d'} radius={.2}/><Block size={[26.6,.12,20.6]} position={[0,.34,0]} color={dark?'#243643':'#eef0e7'} radius={.2}/></group>
<Block size={[7.2,.055,7.3]} position={[-7.4,.32,-3.8]} color={dark?'#2c4555':'#dce6e5'} radius={.15}/><Block size={[9.1,.055,10.4]} position={[7,.32,-2.7]} color={dark?'#3b3a55':'#e7dfed'} radius={.15}/><Block size={[7.2,.055,4.6]} position={[-6.7,.32,6.5]} color={dark?'#46443a':'#eee1ca'} radius={.15}/><Block size={[9.1,.055,4.6]} position={[7,.32,6.5]} color={dark?'#513c4c':'#efdae0'} radius={.15}/>
{[-10,-7,-4,-1,2,5,8].map(z=><Block key={z} size={[26,.008,.012]} position={[.4,.315,z]} color={dark?'#344653':'#d7ddd1'} radius={.003}/>)}<Block size={[26.3,1.6,.13]} position={[.4,1.07,-9.5]} color={dark?'#334756':'#d5ded3'}/><Block size={[.13,1.6,20]} position={[-12.75,1.07,.4]} color={dark?'#334756':'#d5ded3'}/>{[-10.3,-6.2,-2.1,2,6.1,10.2].map(x=><group key={x}><Block size={[3.7,.95,.04]} position={[x,1.3,-9.4]} color={dark?'#213c50':'#d6e4e2'}/><Block size={[.055,1.05,.06]} position={[x,1.3,-9.35]} color={dark?'#586b74':'#a4b8ad'}/></group>)}
<mesh rotation={[-Math.PI/2,0,0]} position={[-.5,.37,.6]}><circleGeometry args={[3.2,64]}/><meshStandardMaterial color={dark?'#385055':'#dae3d3'}/></mesh><Desk position={[-.5,-.3]} active={ceoOnline} executive dark={dark}/><Robot person={ceo} index={19} station={[-.5,-.3]} active={ceoOnline} selected={false} onSelect={onSelect} reduced={reduced} labelsReady={labelsReady} immersive={immersive} preview={!ceoOnline} executive/>
<Block size={[2.6,.11,1.4]} position={[-6.9,1.02,1.7]} color={dark?'#806e59':'#ceb48d'} radius={.18}/>{[-7.7,-6.1].map(x=><Block key={x} size={[.13,.66,.8]} position={[x,.67,1.7]} color="#809286"/>)}<Block size={[.55,.04,.38]} position={[-7.1,1.1,1.7]} color="#f1ecdf"/><Plant position={[-9.6,.3,1.7]}/>
<Block size={[2.7,.65,.85]} position={[.5,.73,7.6]} color={dark?'#52696b':'#acbda0'} radius={.18}/><Block size={[2.7,.45,.16]} position={[.5,1.17,7.96]} color={dark?'#52696b':'#acbda0'} radius={.1}/><Block size={[1.05,.4,.75]} position={[.5,.57,6.35]} color={dark?'#8a7964':'#dfccac'} radius={.13}/><Block size={[2.7,1.7,.11]} position={[.1,1.45,-8.2]} color={dark?'#3d5256':'#f3f4ed'}/><Block size={[2.4,1.35,.015]} position={[.1,1.46,-8.135]} color={dark?'#1f383e':'#d8e5d8'}/>{[0,1,2].map(i=><Block key={i} size={[1.9-i*.25,.05,.012]} position={[.1,1.85-i*.3,-8.12]} color="#8faf9c" radius={.012}/>)}
{[[-11.5,-8],[12,-8],[-11.5,9],[12,9],[-3,8.8],[2.2,2.5]].map(([x,z],i)=><Plant key={i} position={[x,.3,z]}/>)}{agents.map((a,i)=><group key={a.id}><Desk position={stations[i]} active={activeIds.includes(a.id)} creative={a.department==='creative'} dark={dark}/><Robot person={a} index={i} station={stations[i]} active={activeIds.includes(a.id)} selected={selected===a.id} onSelect={onSelect} reduced={reduced} labelsReady={labelsReady} immersive={immersive}/></group>)}<ContactShadows position={[0,.1,0]} opacity={dark?.3:.22} scale={38} blur={2.7} far={10} resolution={256} frames={1}/></Canvas></SceneBoundary>;}
